/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./assets/pengu_featherknight.glb
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/pengu_featherknight.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <group position={[0, 0, -1]}>
          <group name="Meshes" scale={[-0.009, 0.009, 0.009]}>
            <skinnedMesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={materials.Body} skeleton={nodes.mesh_0.skeleton} position={[-54.167, -0.563, -37.576]} scale={0.008} />
          </group>
          <group name="Skeleton" scale={[-0.009, 0.009, 0.009]}>
            <primitive object={nodes.Root} />
            <primitive object={nodes.True_World} />
            <primitive object={nodes.C_Buffbone_Glb_Layout_Loc} />
            <primitive object={nodes.C_Buffbone_Glb_Center_Loc} />
            <primitive object={nodes.Buffbone_Glb_Ground_Loc} />
            <primitive object={nodes.C_Buffbone_Glb_Overhead_Loc} />
            <primitive object={nodes.Buffbone_Glb_Channel_Loc} />
            <primitive object={nodes.Sword_World} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pengu_featherknight.glb')
